# -*- coding: utf-8 -*-
"""FINAL_Major_project plant disease detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16nzpRWCTBZEZssk-BHa1j0V2s6GeK0Qh

## Importing Libraries
"""

import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

print("tensorflow", tf.__version__)
print("matplotlib", plt.matplotlib.__version__)
print("pandas", pd.__version__)
print("seaborn", sns.__version__)

"""#### Dataset Link: https://www.kaggle.com/datasets/vipoooool/new-plant-diseases-dataset

### Extracting kaggle file
"""

import os
from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive')

# Define the correct path to `kaggle.json` inside Google Drive
KAGGLE_JSON_PATH = "/content/drive/MyDrive/Kaggle/kaggle.json"  # Update the folder if needed

# Check if the file exists before copying
if os.path.exists(KAGGLE_JSON_PATH):
    os.makedirs('/root/.kaggle', exist_ok=True)  # Create Kaggle directory if not exists
    os.system(f'cp "{KAGGLE_JSON_PATH}" /root/.kaggle/kaggle.json')  # Copy file
    os.chmod('/root/.kaggle/kaggle.json', 600)  # Set permissions
    print("✅ Kaggle API key successfully copied!")
else:
    print("❌ kaggle.json file NOT FOUND! Please check the file path in Google Drive.")

# Test Kaggle API
!kaggle competitions list

import sys
print("Python", sys.version)
import google.colab
print("google.colab", google.colab.__version__)

"""## Importing Dataset"""

# Create the Kaggle directory and move kaggle.json there
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/

# Set correct permissions
!chmod 600 ~/.kaggle/kaggle.json

# Download the dataset from Kaggle
!kaggle datasets download -d vipoooool/new-plant-diseases-dataset

# Unzip the dataset
!unzip new-plant-diseases-dataset.zip -d /content/new_plant_diseases

"""## Data Preprocessing

### Training Image Preprocessing
"""

train_dataset_path = "/content/new_plant_diseases/New Plant Diseases Dataset(Augmented)/New Plant Diseases Dataset(Augmented)/train"
training_set = tf.keras.utils.image_dataset_from_directory(
    train_dataset_path,
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
)

"""### Validation Image Preprocessing"""

valid_dataset_path = "/content/new_plant_diseases/New Plant Diseases Dataset(Augmented)/New Plant Diseases Dataset(Augmented)/valid"
validation_set = tf.keras.utils.image_dataset_from_directory(
    valid_dataset_path,
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
)

training_set

for x,y in training_set:
    print(x,x.shape)
    print(y,y.shape)
    break

"""### To avoid Overshooting
1. Choose small learning rate default 0.001 we are taking 0.0001
2. There may be chance of Underfitting, so increase number of neuron
3. Add more Convolution layer to extract more feature from images there may be possibilty that model unable to capture relevant feature or model is confusing due to lack of feature so feed with more feature

## Building Model
"""

from tensorflow.keras.layers import Dense,Conv2D,MaxPool2D,Flatten,Dropout
from tensorflow.keras.models import Sequential

import tensorflow as tf

print("tensorflow", tf.__version__)

model = Sequential()

"""## Building Convolution Layer"""

model.add(Conv2D(filters=32,kernel_size=3,padding='same',activation='relu',input_shape=[128,128,3]))
model.add(Conv2D(filters=32,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

model.add(Conv2D(filters=64,kernel_size=3,padding='same',activation='relu'))
model.add(Conv2D(filters=64,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

model.add(Conv2D(filters=128,kernel_size=3,padding='same',activation='relu'))
model.add(Conv2D(filters=128,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

model.add(Conv2D(filters=256,kernel_size=3,padding='same',activation='relu'))
model.add(Conv2D(filters=256,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

model.add(Conv2D(filters=512,kernel_size=3,padding='same',activation='relu'))
model.add(Conv2D(filters=512,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

model.add(Dropout(0.25)) # To avoid Overfitting

model.add(Flatten())

model.add(Dense(units=1500,activation='relu'))

model.add(Dropout(0.4))

#Output Layer
model.add(Dense(units=38,activation='softmax'))

"""### Compiling Model"""

model.compile(optimizer=tf.keras.optimizers.Adam(
    learning_rate=0.0001),loss='categorical_crossentropy',metrics=['accuracy'])

model.summary()

"""### Model Training"""

training_history = model.fit(x=training_set,validation_data=validation_set,epochs=10)

"""## Model Evaluation"""

#Model Evaluation on Training set
train_loss,train_acc = model.evaluate(training_set)

print(train_loss,train_acc)

#Model on Validation set
val_loss,val_acc = model.evaluate(validation_set)

print(val_loss,val_acc)



"""### Saving Model"""

model.save("trained_model.keras")

training_history.history

#Recording History in json
import json
with open("training_hist.json","w") as f:
    json.dump(training_history.history,f)



training_history.history['val_accuracy']

"""### Accuracy Visualization"""

epochs = [i for i in range(1,11)]
plt.plot(epochs,training_history.history['accuracy'],color='red',label='Training Accuracy')
plt.plot(epochs,training_history.history['val_accuracy'],color='blue',label='Validation Accuracy')
plt.xlabel("No. of Epochs")
plt.ylabel("Accuracy Result")
plt.title("Visualization of Accuracy Result")
plt.legend()
plt.show()



"""### Some other metrics for model evaluation"""

class_name = validation_set.class_names
class_name

#using valid dataset as a test dataset because test dataset is not arranged in sequesntial order to test the model

test_dataset_path = "/content/new_plant_diseases/New Plant Diseases Dataset(Augmented)/New Plant Diseases Dataset(Augmented)/valid"
test_set = tf.keras.utils.image_dataset_from_directory(
    test_dataset_path,
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=False,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
)

y_pred = model.predict(test_set)
y_pred,y_pred.shape

predicted_categories = tf.argmax(y_pred,axis=1)

predicted_categories

true_categories = tf.concat([y for x,y in test_set],axis=0)
true_categories

Y_true = tf.argmax(true_categories,axis=1)
Y_true

"""![image.png](attachment:f464cbcc-5d6b-4f32-835c-9aabe0f9c5d4.png)"""

from sklearn.metrics import classification_report,confusion_matrix

print(classification_report(Y_true,predicted_categories,target_names=class_name))

cm = confusion_matrix(Y_true,predicted_categories)
cm



"""### Confusion Matrix Visualization"""

plt.figure(figsize=(40,40))
sns.heatmap(cm,annot=True,annot_kws={'size':10})
plt.xlabel("Predicted Class",fontsize=20)
plt.ylabel("Actual Class",fontsize=20)
plt.title("Plant Disease Prediction Confusion Matrix",fontsize=25)
plt.show()



"""# Plant Disease Treatment

### Importing required libraries
"""

import os
import json
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from tensorflow.keras.optimizers import Adam

print("Python", sys.version)  # Python version
print("os", "Version not available")  # os does not have a version attribute
print("json", "Built-in module, version not applicable")  # json is a built-in module
print("numpy", np.__version__)
print("tensorflow", tf.__version__)
print("keras", keras.__version__)  # Keras version (included in TensorFlow)

"""## Importing Dataset for Treatment of plant disease"""

dataset_path = "/content/new_plant_diseases/New Plant Diseases Dataset(Augmented)/New Plant Diseases Dataset(Augmented)"  # Update with actual dataset path
image_size = (128, 128)  # Resize images
batch_size = 32

datagen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2
)

train_dataset_path = "/content/new_plant_diseases/New Plant Diseases Dataset(Augmented)/New Plant Diseases Dataset(Augmented)/train"
train_generator = datagen.flow_from_directory(
    train_dataset_path,
    target_size=image_size,
    batch_size=batch_size,
    class_mode='categorical',
    subset='training'
)

valid_dataset_path = "/content/new_plant_diseases/New Plant Diseases Dataset(Augmented)/New Plant Diseases Dataset(Augmented)/valid"
val_generator = datagen.flow_from_directory(
    valid_dataset_path,
    target_size=image_size,
    batch_size=batch_size,
    class_mode='categorical',
    subset='validation'
)

num_classes = len(train_generator.class_indices)  # 38 Classes

"""## Building Convolution Layer"""

model = Sequential([
    Conv2D(32, (3, 3), activation='relu', input_shape=(128, 128, 3)),
    MaxPooling2D(2, 2),

    Conv2D(64, (3, 3), activation='relu'),
    MaxPooling2D(2, 2),

    Conv2D(128, (3, 3), activation='relu'),
    MaxPooling2D(2, 2),

    Flatten(),
    Dense(128, activation='relu'),
    Dropout(0.5),
    Dense(num_classes, activation='softmax')
])

model.compile(optimizer=Adam(learning_rate=0.001),
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.summary()

# Print all class labels
print("Class Labels:", train_generator.class_indices)

epochs = 10  # Adjust as needed

history = model.fit(
    train_generator,
    validation_data=val_generator,
    epochs=epochs
)

# Save the trained model
model.save("plant_disease_cnn.h5")

"""# Giving treatment :- Precaution & Cure"""

import tensorflow as tf
import numpy as np
import json
from tensorflow.keras.preprocessing import image

# =========================
# LOAD MODEL
# =========================
model = tf.keras.models.load_model('/content/plant_disease_cnn.h5')
# If needed, replace with:
# model = tf.keras.models.load_model('/content/plant_disease_cnn.h5')

# =========================
# LOAD TREATMENT JSON
# =========================
with open('/content/plant_disease_treatment_38_classes.json', 'r') as f:
    treatment_data = json.load(f)

# =========================
# CLASS NAMES (38 CLASSES)
# =========================
class_names = [
    'Apple___Apple_scab',
    'Apple___Black_rot',
    'Apple___Cedar_apple_rust',
    'Apple___healthy',
    'Blueberry___healthy',
    'Cherry_(including_sour)___Powdery_mildew',
    'Cherry_(including_sour)___healthy',
    'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot',
    'Corn_(maize)___Common_rust_',
    'Corn_(maize)___Northern_Leaf_Blight',
    'Corn_(maize)___healthy',
    'Grape___Black_rot',
    'Grape___Esca_(Black_Measles)',
    'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)',
    'Grape___healthy',
    'Orange___Haunglongbing_(Citrus_greening)',
    'Peach___Bacterial_spot',
    'Peach___healthy',
    'Pepper,_bell___Bacterial_spot',
    'Pepper,_bell___healthy',
    'Potato___Early_blight',
    'Potato___Late_blight',
    'Potato___healthy',
    'Raspberry___healthy',
    'Soybean___healthy',
    'Squash___Powdery_mildew',
    'Strawberry___Leaf_scorch',
    'Strawberry___healthy',
    'Tomato___Bacterial_spot',
    'Tomato___Early_blight',
    'Tomato___Late_blight',
    'Tomato___Leaf_Mold',
    'Tomato___Septoria_leaf_spot',
    'Tomato___Spider_mites Two-spotted_spider_mite',
    'Tomato___Target_Spot',
    'Tomato___Tomato_Yellow_Leaf_Curl_Virus',
    'Tomato___Tomato_mosaic_virus',
    'Tomato___healthy'
]

# =========================
# PREDICTION FUNCTION
# =========================
def predict_plant_disease(image_path):

    img = image.load_img(image_path, target_size=(128, 128))
    img_array = image.img_to_array(img)

    img_array = img_array.astype("float32") / 255.0
    img_array = np.expand_dims(img_array, axis=0)

    prediction = model.predict(img_array, verbose=0)

    predicted_index = np.argmax(prediction[0])
    confidence = float(np.max(prediction[0]))

    disease_name = class_names[predicted_index]

    treatment_info = treatment_data.get(
        disease_name,
        {
            "cure": "No cure information available.",
            "precaution": "No precaution information available."
        }
    )

    print("=" * 60)
    print("Disease Name :", disease_name)
    print("Confidence   :", round(confidence * 100, 2), "%")
    print("Cure         :", treatment_info["cure"])
    print("Precaution   :", treatment_info["precaution"])
    print("=" * 60)

    return disease_name, treatment_info

# =========================
# TEST IMAGE PATH
# =========================
image_path = "/content/new_plant_diseases/test/test/CornCommonRust2.JPG"

predict_plant_disease(image_path)

"""# Testing the image

## Importing Libraries
"""

import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt

"""### Loading Model"""

model  = tf.keras.models.load_model('/content/plant_disease_cnn.h5')

model.summary()



"""### Visualizaing Single Image of Test set"""

!pip install opencv-python

import cv2
print("cv2", cv2.__version__)

import cv2
image_path = "/content/new_plant_diseases/test/test/CornCommonRust2.JPG"
#Reading Image
img = cv2.imread(image_path)
img = cv2.cvtColor(img,cv2.COLOR_BGR2RGB) #Convert BGR image to RGB

#Displaying Image
plt.imshow(img)
plt.title("Test Image")
plt.xticks([])
plt.yticks([])
plt.show()

"""## Testing Model"""

image = tf.keras.preprocessing.image.load_img(image_path,target_size=(128, 128))
input_arr = tf.keras.preprocessing.image.img_to_array(image)
input_arr = np.array([input_arr]) #Convert single image to a batch
print(input_arr.shape)

prediction = model.predict(input_arr)
prediction,prediction.shape

result_index = np.argmax(prediction)
result_index

class_name = ['Apple___Apple_scab',
 'Apple___Black_rot',
 'Apple___Cedar_apple_rust',
 'Apple___healthy',
 'Blueberry___healthy',
 'Cherry_(including_sour)___Powdery_mildew',
 'Cherry_(including_sour)___healthy',
 'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot',
 'Corn_(maize)___Common_rust_',
 'Corn_(maize)___Northern_Leaf_Blight',
 'Corn_(maize)___healthy',
 'Grape___Black_rot',
 'Grape___Esca_(Black_Measles)',
 'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)',
 'Grape___healthy',
 'Orange___Haunglongbing_(Citrus_greening)',
 'Peach___Bacterial_spot',
 'Peach___healthy',
 'Pepper,_bell___Bacterial_spot',
 'Pepper,_bell___healthy',
 'Potato___Early_blight',
 'Potato___Late_blight',
 'Potato___healthy',
 'Raspberry___healthy',
 'Soybean___healthy',
 'Squash___Powdery_mildew',
 'Strawberry___Leaf_scorch',
 'Strawberry___healthy',
 'Tomato___Bacterial_spot',
 'Tomato___Early_blight',
 'Tomato___Late_blight',
 'Tomato___Leaf_Mold',
 'Tomato___Septoria_leaf_spot',
 'Tomato___Spider_mites Two-spotted_spider_mite',
 'Tomato___Target_Spot',
 'Tomato___Tomato_Yellow_Leaf_Curl_Virus',
 'Tomato___Tomato_mosaic_virus',
 'Tomato___healthy']

#Displaying Result of disease prediction
model_prediction = class_name[result_index]
plt.imshow(img)
plt.title(f"Disease Name: {model_prediction}")
plt.xticks([])
plt.yticks([])
plt.show()

import json

with open('/content/plant_disease_treatment_38_classes.json', 'r') as f:
    treatment_data = json.load(f)

import matplotlib.pyplot as plt

# Displaying Result of disease prediction
model_prediction = class_name[result_index]

# Get treatment info directly from JSON using predicted disease
disease_info = treatment_data.get(
    model_prediction,
    {
        "cure": "No treatment information available.",
        "precaution": "No precaution details available."
    }
)

treatment_cure = disease_info["cure"]
treatment_precaution = disease_info["precaution"]

# Format treatment details for display
treatment_text = f"Cure: {treatment_cure}\nPrecaution: {treatment_precaution}"

plt.figure(figsize=(8,6))
plt.imshow(img)
plt.title(
    f"Disease Name: {model_prediction}\n\n"
    f"Cure: {treatment_cure}\n"
    f"Precaution: {treatment_precaution}",
    fontsize=10
)
plt.xticks([])
plt.yticks([])
plt.show()

model_prediction

treatment_cure

treatment_precaution

# Assuming 'model' is your trained Keras model
model.save("model.h5")
print("CNN Model saved successfully! in h5")

# Assuming 'model' is your trained Keras model
model.save("model.keras")
print("CNN Model saved successfully! in keras")

